// 日本語テキスト定数

export const JA = {
  // 共通
  common: {
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    add: '追加',
    search: '検索',
    filter: 'フィルター',
    export: 'エクスポート',
    back: '戻る',
    next: '次へ',
    previous: '前へ',
    submit: '送信',
    confirm: '確認',
    loading: '読み込み中...',
    success: '成功しました',
    error: 'エラーが発生しました',
    noData: 'データがありません',
    actions: '操作',
  },

  // 認証
  auth: {
    login: 'ログイン',
    logout: 'ログアウト',
    register: '新規登録',
    loginId: 'ログインID / メール',
    password: 'パスワード',
    forgotPassword: 'パスワードをお忘れですか？',
    resetPassword: 'パスワードリセット',
    changePassword: 'パスワード変更',
    newPassword: '新しいパスワード',
    confirmPassword: 'パスワード確認',
    oldPassword: '現在のパスワード',
    loginSuccess: 'ログインしました',
    logoutSuccess: 'ログアウトしました',
    loginFailed: 'ログインに失敗しました',
    registerSuccess: '登録が完了しました',
    passwordResetSuccess: 'パスワードリセットメールを送信しました',
    passwordChangeSuccess: 'パスワードを変更しました',
    emailPlaceholder: 'メールアドレスを入力してください',
    passwordPlaceholder: 'パスワードを入力してください',
    loginRequired: 'ログインIDを入力してください',
    passwordRequired: 'パスワードを入力してください',
  },

  // ナビゲーション
  nav: {
    home: 'ホーム',
    dashboard: 'ダッシュボード',
    profile: 'プロフィール',
    master: 'マスタ管理',
    employees: '従業員管理',
    equipments: '重機管理',
    contractors: 'ゼネコン管理',
    booking: '重機予約',
    bookingList: '予約一覧',
    myBookings: 'マイ予約',
    schedule: 'スケジュール',
    calendar: 'カレンダー表示',
    dailyList: '日別一覧',
    boardMode: 'ボードモード',
    certificates: '工程表',
    history: '変更履歴',
    notifications: '通知',
    users: 'ユーザー管理',
  },

  // ダッシュボード
  dashboard: {
    title: '管理ダッシュボード',
    welcomeBack: 'おかえりなさい',
    totalBookings: '総予約数',
    pendingApprovals: '承認待ち',
    totalEquipments: '総重機数',
    activeUsers: 'アクティブユーザー',
    recentBookings: '最近の予約',
    recentCertificates: '最近の工程表',
    viewAll: 'すべて表示',
    stats: '統計情報',
  },

  // ホーム（Individual用）
  home: {
    title: 'ホーム',
    welcome: 'ようこそ',
    equipmentSchedule: '重機スケジュール',
    myBookings: 'マイ予約',
    timeline: 'タイムライン',
    todaySchedule: '本日のスケジュール',
    upcomingBookings: '今後の予約',
  },

  // 重機予約
  booking: {
    title: '重機予約管理',
    createBooking: '新規予約',
    editBooking: '予約編集',
    bookingDetail: '予約詳細',
    equipment: '重機',
    selectEquipment: '重機を選択',
    startDate: '開始日時',
    endDate: '終了日時',
    purpose: '使用目的',
    status: 'ステータス',
    pending: '承認待ち',
    approved: '承認済み',
    rejected: '却下',
    completed: '完了',
    cancelled: 'キャンセル',
    draft: '下書き',
    approve: '承認',
    reject: '却下',
    cancel: 'キャンセル',
    duplicate: '複製',
    saveDraft: '下書き保存',
    bookingDate: '予約日',
    bookedBy: '予約者',
    approveConfirm: 'この予約を承認しますか？',
    rejectConfirm: 'この予約を却下しますか？',
    deleteConfirm: 'この予約を削除しますか？',
    bookingSuccess: '予約を作成しました',
    approveSuccess: '予約を承認しました',
    rejectSuccess: '予約を却下しました',
    deleteSuccess: '予約を削除しました',
    updateSuccess: '予約を更新しました',
    rejectReason: '却下理由',
    enterReason: '理由を入力してください',
  },

  // 重機管理
  equipment: {
    title: '重機管理',
    name: '重機名',
    category: 'カテゴリー',
    serialNumber: 'シリアル番号',
    manufacturer: 'メーカー',
    model: 'モデル',
    status: 'ステータス',
    available: '利用可能',
    inUse: '使用中',
    maintenance: 'メンテナンス中',
    unavailable: '利用不可',
    addEquipment: '重機追加',
    editEquipment: '重機編集',
    deleteConfirm: 'この重機を削除しますか？',
    createSuccess: '重機を追加しました',
    updateSuccess: '重機を更新しました',
    deleteSuccess: '重機を削除しました',
  },

  // 従業員管理
  employee: {
    title: '従業員管理',
    name: '氏名',
    email: 'メール',
    phone: '電話番号',
    position: '役職',
    department: '部署',
    addEmployee: '従業員追加',
    editEmployee: '従業員編集',
    deleteConfirm: 'この従業員を削除しますか？',
    createSuccess: '従業員を追加しました',
    updateSuccess: '従業員を更新しました',
    deleteSuccess: '従業員を削除しました',
  },

  // ユーザー管理
  user: {
    title: 'ユーザー管理',
    username: 'ユーザー名',
    email: 'メール',
    role: 'ロール',
    admin: '管理者',
    individual: '一般ユーザー',
    status: 'ステータス',
    active: 'アクティブ',
    inactive: '無効',
    lastLogin: '最終ログイン',
    createdAt: '作成日',
    addUser: 'ユーザー追加',
    editUser: 'ユーザー編集',
    assignRole: 'ロール割り当て',
    resetPassword: 'パスワードリセット',
    resetPasswordConfirm: 'このユーザーのパスワードをリセットしますか？',
    deleteConfirm: 'このユーザーを削除しますか？',
    createSuccess: 'ユーザーを追加しました',
    updateSuccess: 'ユーザーを更新しました',
    deleteSuccess: 'ユーザーを削除しました',
    resetSuccess: 'パスワードリセットメールを送信しました',
  },

  // ゼネコン管理
  contractor: {
    title: 'ゼネコン管理',
    name: '会社名',
    contactPerson: '担当者',
    email: 'メール',
    phone: '電話番号',
    address: '住所',
    addContractor: 'ゼネコン追加',
    editContractor: 'ゼネコン編集',
    deleteConfirm: 'このゼネコンを削除しますか？',
    createSuccess: 'ゼネコンを追加しました',
    updateSuccess: 'ゼネコンを更新しました',
    deleteSuccess: 'ゼネコンを削除しました',
  },

  // 工程表
  certificate: {
    title: '工程表管理',
    upload: 'アップロード',
    fileName: 'ファイル名',
    fileType: 'ファイル形式',
    uploadDate: 'アップロード日',
    uploadedBy: 'アップロード者',
    status: 'ステータス',
    pending: '承認待ち',
    approved: '承認済み',
    rejected: '却下',
    approve: '承認',
    reject: '却下',
    download: 'ダウンロード',
    deleteConfirm: 'このファイルを削除しますか？',
    uploadSuccess: 'アップロードしました',
    approveSuccess: '承認しました',
    rejectSuccess: '却下しました',
    deleteSuccess: '削除しました',
    selectFile: 'ファイルを選択',
    dragDrop: 'ファイルをドラッグ＆ドロップ',
    supportedFormats: '対応形式: PDF, Excel, 画像',
  },

  // 履歴
  history: {
    title: '変更履歴',
    action: 'アクション',
    created: '作成',
    updated: '更新',
    deleted: '削除',
    entity: 'エンティティ',
    user: 'ユーザー',
    timestamp: '日時',
    changes: '変更内容',
    noHistory: '履歴がありません',
  },

  // 通知
  notification: {
    title: '通知',
    markAsRead: '既読にする',
    markAllAsRead: 'すべて既読にする',
    noNotifications: '通知がありません',
    bookingCreated: '予約が作成されました',
    bookingApproved: '予約が承認されました',
    bookingRejected: '予約が却下されました',
    bookingCancelled: '予約がキャンセルされました',
  },

  // プロフィール
  profile: {
    title: 'プロフィール',
    viewProfile: 'プロフィール表示',
    editProfile: 'プロフィール編集',
    name: '氏名',
    email: 'メール',
    phone: '電話番号',
    role: 'ロール',
    updateSuccess: 'プロフィールを更新しました',
  },

  // カレンダー
  calendar: {
    today: '今日',
    month: '月',
    week: '週',
    day: '日',
    list: '一覧',
    agenda: 'アジェンダ',
    allEquipments: '全重機',
    clickToBook: 'クリックして予約',
    dragToMove: 'ドラッグして移動',
    selectTime: '時間を選択',
    startTime: '開始時刻',
    endTime: '終了時刻',
    noEvents: '予約がありません',
  },

  // テーブル
  table: {
    page: 'ページ',
    of: '/',
    items: '件',
    rowsPerPage: '行/ページ',
    noData: 'データがありません',
  },

  // エラーメッセージ
  error: {
    required: 'この項目は必須です',
    invalidEmail: '有効なメールアドレスを入力してください',
    passwordMismatch: 'パスワードが一致しません',
    minLength: '最低{min}文字必要です',
    maxLength: '最大{max}文字まで',
    networkError: 'ネットワークエラーが発生しました',
    serverError: 'サーバーエラーが発生しました',
    unauthorized: '権限がありません',
    notFound: '見つかりませんでした',
  },
};

export default JA;
